# Generated by Django 4.1.2 on 2022-10-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
