# Generated by Django 4.1.2 on 2022-10-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_alter_song_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='img',
            field=models.ImageField(upload_to='image'),
        ),
    ]
