# Generated by Django 4.1.2 on 2022-10-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stage', models.CharField(max_length=200, unique=True)),
                ('Social_link', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Album', max_length=200, verbose_name='New Album')),
                ('pub_date', models.DateTimeField(unique=True, verbose_name='date published')),
                ('release', models.DateTimeField(verbose_name='release published')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
        ),
    ]
