# Generated by Django 4.1.2 on 2022-10-08 17:52

import artists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_social_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='Stage',
            field=models.CharField(max_length=200, unique=True, validators=[artists.models.validate]),
        ),
    ]
