# Generated by Django 4.1.2 on 2022-10-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_album_album_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='assgin',
            field=models.DecimalField(decimal_places=999, default=0, max_digits=999),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_is_approved',
            field=models.BooleanField(default=True, help_text=' Approve the album if its name is not explicit'),
        ),
    ]
