# Generated by Django 4.1.2 on 2022-10-09 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_artist_assgin_alter_album_album_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='assgin',
            field=models.IntegerField(default=0),
        ),
    ]
