# Generated by Django 4.1.2 on 2022-10-10 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artist_assgin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='assgin',
        ),
    ]
