# Generated by Django 4.1.2 on 2022-10-15 00:34

import artists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='New Album', max_length=200, validators=[artists.models.validate], verbose_name='New Album'),
        ),
    ]
