# Generated by Django 4.1.2 on 2022-10-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='New Album', max_length=200, verbose_name='New Album'),
        ),
    ]
