# Generated by Django 4.1.2 on 2022-10-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release',
            field=models.DateTimeField(),
        ),
    ]
