# Generated by Django 4.1.2 on 2022-10-23 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_alter_album_release'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
